-- MySQL Script generated by MySQL Workbench
-- Fri Sep 30 21:18:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco` DEFAULT CHARACTER SET utf8 ;
USE `banco` ;

-- -----------------------------------------------------
-- Table `banco`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`clientes` (
  `id_cliente` DECIMAL(10) NOT NULL COMMENT 'ID de los clientes',
  `nombre_cliente` VARCHAR(45) NOT NULL COMMENT 'nombre cliente',
  `apellido_cliente` VARCHAR(45) NOT NULL COMMENT 'apellido cliente',
  `genero_cliente` BLOB NOT NULL COMMENT '1: masculino\n2: femenino\n3: no definido',
  `telefono_cliente` DECIMAL(12) NOT NULL,
  `mail_cliente` VARCHAR(35) NOT NULL,
  `numero_documento` DECIMAL(10) NOT NULL COMMENT 'no lo declaro como unique key ya que, para alguna prueba quiza funcione tener 2 personas con el mismo DU (para testear unique keys, por ej)',
  `numero_tributario` DECIMAL(13) NOT NULL COMMENT 'mas conocido como CUIT o CUIL',
  `fecha_nacimiento` NVARCHAR(6) NOT NULL COMMENT 'fecha nacimiento del cliente',
  `tipo_cliente` INT NOT NULL COMMENT 'esta tabla en un futuro podria ser en base a los haberes\nmientras mas ingreso > mejores beneficios',
  `estado_civil` INT NOT NULL COMMENT 'S: soltero\nC: casado\nP: en pareja\nD: divorciado\nX: no contesta\n',
  `profesion` VARCHAR(40) NULL COMMENT 'descripcion breve del empleo que tiene\npuede ser nulo',
  `nacionalidad` INT NOT NULL,
  `fecha_alta` NVARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_cliente`, `numero_documento`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC) VISIBLE,
  UNIQUE INDEX `nro_tributario_UNIQUE` (`numero_tributario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`clientes_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`clientes_productos` (
  `id_cliente` DECIMAL(10) NOT NULL,
  `id_cuenta` DECIMAL(12) NOT NULL,
  `tipo_producto` INT NOT NULL COMMENT '1:tarjetas credito\n2:tarjeta debito\n3: caja de ahorro\n4: cuenta corriente\n5: prestamos\n6: inversiones\n',
  `tipo_moneda` INT NOT NULL COMMENT '1: pesos\n2: dolares',
  `fecha_alta` NVARCHAR(6) NOT NULL COMMENT 'es un timestamp de cuando se crea',
  `fecha_baja` NVARCHAR(6) NOT NULL COMMENT 'puede ser nulo ya que no tiene fecha de baja',
  INDEX `fk_table1_clientes_idx` (`id_cliente` ASC) VISIBLE,
  UNIQUE INDEX `clientes_id_cliente_UNIQUE` (`id_cliente` ASC) VISIBLE,
  PRIMARY KEY (`id_cliente`, `id_cuenta`),
  UNIQUE INDEX `codigo_prod_UNIQUE` (`id_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_table1_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `banco`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`tipo_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`tipo_productos` (
  `tipo_productos` INT NOT NULL COMMENT '1:tarjetas credito\n2:tarjeta debito\n3: caja de ahorro\n4: cuenta corriente\n5: prestamos\n6: inversiones\n',
  `descripcion` VARCHAR(45) NULL COMMENT '1:tarjetas credito\n2:tarjeta debito\n3: caja de ahorro\n4: cuenta corriente\n5: prestamos\n6: inversiones\n',
  UNIQUE INDEX `inversiones_UNIQUE` () VISIBLE,
  UNIQUE INDEX `tipo_producto_UNIQUE` (`tipo_productos` ASC) VISIBLE,
  INDEX `fk_tipo_productos_productos1_idx` (`tipo_productos` ASC, `descripcion` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_productos_productos1`
    FOREIGN KEY (`tipo_productos` , `descripcion`)
    REFERENCES `banco`.`clientes_productos` (`tipo_producto` , `tipo_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`tipo_moneda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`tipo_moneda` (
  `tipo_moneda` INT NOT NULL COMMENT '1:pesos\n2:dolares\n3:euros\n4:reales\n5:libra esterlina\n6:peso chileno\n7:peso uruguayo',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '1:pesos\n2:dolares\n3:euros\n4:reales\n5:libra esterlina\n6:peso chileno\n7:peso uruguayo',
  UNIQUE INDEX `pesos_UNIQUE` (`tipo_moneda` ASC) VISIBLE,
  INDEX `fk_tipo_moneda_productos1_idx` (`tipo_moneda` ASC, `descripcion` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_moneda_productos1`
    FOREIGN KEY (`tipo_moneda` , `descripcion`)
    REFERENCES `banco`.`clientes_productos` (`tipo_moneda` , `tipo_moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`clientes_tarjetas_debito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`clientes_tarjetas_debito` (
  `numero_tarjeta` DECIMAL(16) NOT NULL,
  `id_marca_tarjeta` INT NOT NULL,
  `id_cuenta` DECIMAL(12) NOT NULL,
  `tipo_moneda` INT NOT NULL,
  `fecha_alta` NVARCHAR(6) NOT NULL,
  `fecha_baja` NVARCHAR(6) NOT NULL,
  PRIMARY KEY (`numero_tarjeta`),
  UNIQUE INDEX `numero_tarjeta_UNIQUE` (`numero_tarjeta` ASC) VISIBLE,
  UNIQUE INDEX `codigo_prod_UNIQUE` (`id_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_tarjeta_debito_rel_cliente_prod1`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `banco`.`clientes_productos` (`id_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`clientes_tarjeta_credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`clientes_tarjeta_credito` (
  `numero_tarjeta` DECIMAL(16) NOT NULL,
  `id_marca_tarjeta` INT NOT NULL,
  `id_cuenta` DECIMAL(12) NOT NULL,
  `tipo_moneda` INT NOT NULL,
  `fecha_alta` NVARCHAR(6) NOT NULL,
  `fecha_baja` NVARCHAR(6) NOT NULL,
  PRIMARY KEY (`numero_tarjeta`),
  UNIQUE INDEX `num_tarjeta_UNIQUE` (`numero_tarjeta` ASC) VISIBLE,
  UNIQUE INDEX `codigo_prod_UNIQUE` (`id_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_tarjeta_credito_rel_cliente_prod1`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `banco`.`clientes_productos` (`id_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`tipo_tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`tipo_tarjeta` (
  `id_marca_tarjeta` INT NOT NULL COMMENT '1:VISA\n2:MASTERCARD\n3:AMEX\n4:BANELCO\n5:ELECTRON\n6:CABAL',
  `descripcion` VARCHAR(10) NOT NULL COMMENT '1:VISA\n2:MASTERCARD\n3:AMEX\n4:BANELCO\n5:ELECTRON\n6:CABAL',
  UNIQUE INDEX `id_tarjeta_UNIQUE` (`id_marca_tarjeta` ASC),
  CONSTRAINT `fk_tipo_tarjeta_tarjeta_debito1`
    FOREIGN KEY (`id_marca_tarjeta`)
    REFERENCES `banco`.`clientes_tarjetas_debito` (`id_marca_tarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_tarjeta_tarjeta_credito1`
    FOREIGN KEY (`id_marca_tarjeta`)
    REFERENCES `banco`.`clientes_tarjeta_credito` (`id_marca_tarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`clientes_cuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`clientes_cuentas` (
  `id_cuenta` DECIMAL(12) NOT NULL,
  `tipo_cuenta` DECIMAL(1) NOT NULL,
  `tipo_moneda` INT NOT NULL,
  `fecha_alta` NVARCHAR(6) NOT NULL,
  `fecha_baja` NVARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_cuenta`),
  UNIQUE INDEX `id_cuenta_UNIQUE` (`id_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_cuentas_rel_cliente_prod1`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `banco`.`clientes_productos` (`id_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`clientes_inversiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`clientes_inversiones` (
  `id_inversion` DECIMAL(8) NOT NULL,
  `tipo_inversion` INT NOT NULL,
  `id_cuenta` DECIMAL(12) NOT NULL,
  `tipo_moneda` INT NOT NULL,
  `fecha_alta` NVARCHAR(6) NOT NULL,
  `fecha_baja` NVARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_inversion`, `id_cuenta`),
  UNIQUE INDEX `id_inversion_UNIQUE` (`id_inversion` ASC) VISIBLE,
  UNIQUE INDEX `id_cuenta_UNIQUE` (`id_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_cli_inversion_rel_cliente_prod1`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `banco`.`clientes_productos` (`id_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`tipo_inversion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`tipo_inversion` (
  `tipo_inversion` INT NOT NULL COMMENT '1:plazo fijo\n2:plazo fijo UVA\n3:FCI\n4:etc\n',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '1:plazo fijo\n2:plazo fijo UVA\n3:FCI\n4:etc',
  UNIQUE INDEX `tipo_inversion_UNIQUE` (`tipo_inversion` ASC),
  CONSTRAINT `fk_tipo_inversion_cli_inversion1`
    FOREIGN KEY (`tipo_inversion`)
    REFERENCES `banco`.`clientes_inversiones` (`tipo_inversion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`tipo_cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`tipo_cuenta` (
  `tipo_cuenta` INT NULL COMMENT '1:caja de ahorro\n2:cuenta corriente\n3:caja de ahorro dolares\n4:cuenta corriente dolares',
  `descripcion` VARCHAR(45) NULL COMMENT '1:caja de ahorro\n2:cuenta corriente\n3:caja de ahorro dolares\n4:cuenta corriente dolares',
  UNIQUE INDEX `tipo_cuenta_UNIQUE` (`tipo_cuenta` ASC),
  CONSTRAINT `fk_tipo_cuenta_cli_cuentas1`
    FOREIGN KEY (`tipo_cuenta`)
    REFERENCES `banco`.`clientes_cuentas` (`tipo_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`clientes_prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`clientes_prestamos` (
  `id_prestamo` DECIMAL(8) NOT NULL,
  `tipo_prestamo` INT NOT NULL,
  `id_cuenta` DECIMAL(12) NOT NULL,
  `tipo_moneda` INT NOT NULL,
  `fecha_alta` NVARCHAR(6) NOT NULL,
  `fecha_baja` NVARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_prestamo`),
  INDEX `fk_cli_prestamos_rel_cliente_prod1_idx` (`id_cuenta` ASC) VISIBLE,
  UNIQUE INDEX `id_cuenta_UNIQUE` (`id_cuenta` ASC) VISIBLE,
  UNIQUE INDEX `id_prestamo_UNIQUE` (`id_prestamo` ASC) VISIBLE,
  CONSTRAINT `fk_cli_prestamos_rel_cliente_prod1`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `banco`.`clientes_productos` (`id_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`tipo_prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`tipo_prestamo` (
  `tipo_prestamo` INT NOT NULL COMMENT '1:personal\n2:empresa\n3:hipotecario\n4:estudios',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '1:personal\n2:empresa\n3:hipotecario\n4:estudios',
  UNIQUE INDEX `tipo_prestamo_UNIQUE` (`tipo_prestamo` ASC),
  CONSTRAINT `fk_tipo_prestamo_cli_prestamos1`
    FOREIGN KEY (`tipo_prestamo`)
    REFERENCES `banco`.`clientes_prestamos` (`tipo_prestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
